### ISSUE TITLE
Create a tool to save a video for each episode of the agent

### ISSUE THREAD

**Issue by DanielCoelho112** [DanielCoelho112/curlad#3]
The video should contain the controls taken by the agent, the next waypoints given by the global planner, and additional information.

**Comment by miguelriemoliveira** [comment]
How abot a video with the raw image and a json file with the additional
data per frame.

Then, you write an opencv script that reads both and shows the annotated
video.

**Comment by DanielCoelho112** [comment]
Hi @miguelriemoliveira,

yes, nice idea. This way we won't waste unnecessary time during training, and we can always change the annotated images since we have the raw data.

**Comment by miguelriemoliveira** [comment]
Right, and we can use the json file to improve the visualization afterwards.
If we write directly in the image we cannot change afterwards.
I know because I did this a long time ago:

https://www.youtube.com/watch?v=pZSB54petG4

The annotations were all done with cv puttexts and cvlines directly in the images.

**Comment by DanielCoelho112** [comment]
Done. Check an example with a dummy agent:

https://uapt33090-my.sharepoint.com/:v:/g/personal/danielsilveiracoelho_ua_pt/EX0eJnUi8zdIsPlLzzGUZXoB_-KxRRQkxVIrfAYd1KHhOA?e=5hHEOW

The green points are the waypoints provided by the global planner.

**Comment by miguelriemoliveira** [comment]
Looks great!

**Comment by vitoruapt** [comment]
2 seconds of video that look promising :-)
